workflows:
  ios-pwa-workflow:
    name: iOS App Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
    scripts:
      - name: Inspect project
        script: |
          ls -la
    artifacts:
      - build/ios/ipa/*.ipa
